[package]
name = "tortank"
version = "0.1.17"
edition = "2021"
authors = ["Nordine Bittich <contact@bittich.be>"]
description = "Turtle/N3 parser"
categories = ["database"]
license = "MIT"
homepage = "https://github.com/nbittich/tortank"
repository = "https://github.com/nbittich/tortank"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde = "1.0.188"
serde_derive = "1.0.188"
uuid = { version = "1.4.1", features = ["v4"] }

serde_json = "1.0.105"
chrono = "0.4.28"

# The profile that 'cargo dist' will build with
[profile.release]
opt-level = 'z'
codegen-units = 1
panic = 'abort'
strip = "symbols"
lto = "thin"
