[package]
name = "tortank"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
categories = ["database"]
description.workspace = true

[dependencies]
nom.workspace = true
serde.workspace = true
serde_derive.workspace = true
uuid.workspace = true
serde_json.workspace = true
chrono.workspace = true
nom-language.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { workspace = true, features = ["js"] }

[dev-dependencies]
serial_test.workspace = true
test-case.workspace = true
